# Pertemuan 5: Support Vector Machine (SVM)
Nama : ILMA AQSARI

NIM : 105841108023

Penjelasan:

Pada pertemuan ini mempelajari algoritma Support Vector Machine (SVM)
menggunakan dataset Breast Cancer.

Tahapan yang dilakukan:
1. Load dataset Breast Cancer
2. Membagi data training dan testing
3. Melakukan normalisasi data menggunakan StandardScaler
4. Melatih model SVM dengan kernel Linear dan RBF
5. Membandingkan akurasi model
6. Melakukan tuning parameter C dan gamma

Tujuan praktikum ini adalah memahami cara kerja SVM
dan pengaruh parameter terhadap hasil klasifikasi.

## Import Library

In [1]:
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

## 1. Load Dataset

In [2]:
print("="*60)
print("LOAD DATASET BREAST CANCER")
print("="*60)

data = load_breast_cancer()

print("Jumlah data :", data.data.shape)
print("Jumlah fitur:", len(data.feature_names))
print("Nama kelas  :", data.target_names)

LOAD DATASET BREAST CANCER
Jumlah data : (569, 30)
Jumlah fitur: 30
Nama kelas  : ['malignant' 'benign']


In [3]:
print("\nContoh Data:")
print(data.data[:5])

print("\nContoh Target:")
print(data.target[:5])


Contoh Data:
[[1.799e+01 1.038e+01 1.228e+02 1.001e+03 1.184e-01 2.776e-01 3.001e-01
  1.471e-01 2.419e-01 7.871e-02 1.095e+00 9.053e-01 8.589e+00 1.534e+02
  6.399e-03 4.904e-02 5.373e-02 1.587e-02 3.003e-02 6.193e-03 2.538e+01
  1.733e+01 1.846e+02 2.019e+03 1.622e-01 6.656e-01 7.119e-01 2.654e-01
  4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 1.326e+03 8.474e-02 7.864e-02 8.690e-02
  7.017e-02 1.812e-01 5.667e-02 5.435e-01 7.339e-01 3.398e+00 7.408e+01
  5.225e-03 1.308e-02 1.860e-02 1.340e-02 1.389e-02 3.532e-03 2.499e+01
  2.341e+01 1.588e+02 1.956e+03 1.238e-01 1.866e-01 2.416e-01 1.860e-01
  2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 1.203e+03 1.096e-01 1.599e-01 1.974e-01
  1.279e-01 2.069e-01 5.999e-02 7.456e-01 7.869e-01 4.585e+00 9.403e+01
  6.150e-03 4.006e-02 3.832e-02 2.058e-02 2.250e-02 4.571e-03 2.357e+01
  2.553e+01 1.525e+02 1.709e+03 1.444e-01 4.245e-01 4.504e-01 2.430e-01
  3.613e-01 8.758e-02]
 [1.142e+01 2.038e+01 7.758e+01 3.861e+02 1.425e-01 2

In [4]:
print("\nStatistik Fitur (5 pertama):")
print(np.round(data.data[:,:5].mean(axis=0),2))


Statistik Fitur (5 pertama):
[1.4130e+01 1.9290e+01 9.1970e+01 6.5489e+02 1.0000e-01]


## 2. Split Data Training & Testing

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    data.data,
    data.target,
    test_size=0.2,
    random_state=42
)

print("\nUkuran Training :", X_train.shape)
print("Ukuran Testing  :", X_test.shape)


Ukuran Training : (455, 30)
Ukuran Testing  : (114, 30)


## 3. Scaling Data (WAJIB untuk SVM)

In [6]:
print("\nMelakukan StandardScaler...")

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print("\nSetelah scaling:")
print("Mean (mendekati 0):", np.round(X_train.mean(),2))
print("Std (mendekati 1):", np.round(X_train.std(),2))


Melakukan StandardScaler...

Setelah scaling:
Mean (mendekati 0): -0.0
Std (mendekati 1): 1.0


## 4. Tugas 1 - Perbandingan Kernel Linear vs RBF

In [7]:
print("\n" + "="*60)
print("TUGAS 1: PERBANDINGAN KERNEL SVM")
print("="*60)

models = {
    "SVM Linear" : SVC(kernel="linear", C=1),
    "SVM RBF" : SVC(kernel="rbf", C=1, gamma="scale")
}
hasil = {}

for nama, model in models.items():
    model.fit(X_train,y_train)
    pred = model.predict(X_test)
    acc = accuracy_score(y_test,pred)
    hasil[nama] = acc

    print("\nModel :", nama)
    print("Accuracy :", round(acc,3))
    print("\nClassification Report")
    print(classification_report(
        y_test,
        pred,
        target_names=data.target_names
    ))
    print("Confusion Matrix")
    print(confusion_matrix(y_test,pred))


TUGAS 1: PERBANDINGAN KERNEL SVM

Model : SVM Linear
Accuracy : 0.956

Classification Report
              precision    recall  f1-score   support

   malignant       0.93      0.95      0.94        43
      benign       0.97      0.96      0.96        71

    accuracy                           0.96       114
   macro avg       0.95      0.96      0.95       114
weighted avg       0.96      0.96      0.96       114

Confusion Matrix
[[41  2]
 [ 3 68]]

Model : SVM RBF
Accuracy : 0.982

Classification Report
              precision    recall  f1-score   support

   malignant       1.00      0.95      0.98        43
      benign       0.97      1.00      0.99        71

    accuracy                           0.98       114
   macro avg       0.99      0.98      0.98       114
weighted avg       0.98      0.98      0.98       114

Confusion Matrix
[[41  2]
 [ 0 71]]


In [8]:
print("\nInsight Kernel:")
print("Kernel Linear cocok untuk data yang terpisah secara linear")
print("Kernel RBF lebih fleksibel untuk pola yang kompleks")


Insight Kernel:
Kernel Linear cocok untuk data yang terpisah secara linear
Kernel RBF lebih fleksibel untuk pola yang kompleks


## 5. Tugas 2 - Tuning Parameter

In [9]:
print("\n" + "="*60)
print("TUGAS 2: TUNING PARAMETER")
print("="*60)

best_accuracy = 0
best_param = {}

for C in [0.1,1,10]:
    for gamma in [0.01,0.1,1]:

        model = SVC(
            kernel="rbf",
            C=C,
            gamma=gamma
        )

        model.fit(X_train,y_train)
        pred = model.predict(X_test)
        acc = accuracy_score(y_test,pred)

        print("C =",C,"gamma =",gamma,"accuracy =",round(acc,3))
        if acc > best_accuracy:
            best_accuracy = acc
            best_param = {
                "C":C,
                "gamma":gamma
            }
print("\nParameter Terbaik")
print(best_param)
print("Best Accuracy:",round(best_accuracy,3))


TUGAS 2: TUNING PARAMETER
C = 0.1 gamma = 0.01 accuracy = 0.965
C = 0.1 gamma = 0.1 accuracy = 0.947
C = 0.1 gamma = 1 accuracy = 0.623
C = 1 gamma = 0.01 accuracy = 0.965
C = 1 gamma = 0.1 accuracy = 0.965
C = 1 gamma = 1 accuracy = 0.632
C = 10 gamma = 0.01 accuracy = 0.982
C = 10 gamma = 0.1 accuracy = 0.965
C = 10 gamma = 1 accuracy = 0.632

Parameter Terbaik
{'C': 10, 'gamma': 0.01}
Best Accuracy: 0.982


In [10]:
print("\nInterpretasi Parameter:")
print("C besar membuat model lebih fokus pada data training")
print("Gamma besar membuat batas keputusan lebih kompleks")


Interpretasi Parameter:
C besar membuat model lebih fokus pada data training
Gamma besar membuat batas keputusan lebih kompleks


## 6. Kesimpulan

In [11]:
print("\n" + "="*60)
print("KESIMPULAN")
print("="*60)

print("1. Kernel RBF biasanya menghasilkan akurasi lebih baik")
print("   dibanding kernel Linear pada dataset ini.")

print("2. Parameter C dan gamma mempengaruhi batas keputusan SVM.")

print("3. Scaling menggunakan StandardScaler wajib dilakukan")
print("   agar performa SVM optimal.")


KESIMPULAN
1. Kernel RBF biasanya menghasilkan akurasi lebih baik
   dibanding kernel Linear pada dataset ini.
2. Parameter C dan gamma mempengaruhi batas keputusan SVM.
3. Scaling menggunakan StandardScaler wajib dilakukan
   agar performa SVM optimal.


In [12]:
print("\n✅ Pertemuan 5 Selesai")


✅ Pertemuan 5 Selesai
